import { expect, test } from "../fixtures";
import { readFile } from "node:fs/promises";
import { adminLibraryPhrases } from "../../data/library-reference";

test("keep a speaking attempt while changing preferences and reloading", async ({ page }) => {
  await page.clock.setFixedTime(new Date("2026-10-06T12:00:00.000Z"));
  await page.goto("/");
  await page.getByRole("button", { name: /Speak Kannada.*Choose speaking/ }).click();
  await page.getByRole("button", { name: "Reveal and compare", exact: true }).click();
  await page.getByRole("button", { name: "Said it", exact: true }).click();
  const saved = await page.evaluate(() => localStorage.getItem("kannada-buddy-learning-state-v2"));
  expect(saved).not.toBeNull();
  await page.goto("/settings");
  await page.getByRole("button", { name: "Speak + read", exact: true }).click();
  await page.getByRole("button", { name: "10 min", exact: true }).click();
  await page.reload();
  await expect(page.getByRole("button", { name: "Speak + read", exact: true })).toHaveAttribute("aria-pressed", "true");
  await expect(page.getByRole("button", { name: "10 min", exact: true })).toHaveAttribute("aria-pressed", "true");
  expect(await page.evaluate(() => localStorage.getItem("kannada-buddy-learning-state-v2"))).toBe(saved);
  const preferences = await page.evaluate(() => localStorage.getItem("kannada-buddy-learning-preferences-v2"));
  if (!saved || !preferences) throw new Error("Progress and preferences must exist before backup.");
  const downloaded = page.waitForEvent("download");
  await page.getByRole("button", { name: "Download backup", exact: true }).click();
  const path = await (await downloaded).path();
  if (!path) throw new Error("The synthetic backup was not downloaded.");
  const bytes = await readFile(path);
  expect(JSON.parse(bytes.toString()).data.learning).toEqual(JSON.parse(saved));
  await page.evaluate(() => {
    localStorage.removeItem("kannada-buddy-learning-state-v2");
    localStorage.removeItem("kannada-buddy-learning-preferences-v2");
  });
  await page.reload();
  await page.getByLabel("Choose a backup to restore").setInputFiles({ name: "synthetic-backup.json", mimeType: "application/json", buffer: bytes });
  await expect(page.getByText(/1 practised concepts/)).toBeVisible();
  expect(await page.evaluate(() => localStorage.getItem("kannada-buddy-learning-state-v2"))).toBeNull();
  await page.getByRole("button", { name: "Restore backup", exact: true }).click();
  await expect(page.getByRole("status")).toContainText("Backup restored on this browser");
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem("kannada-buddy-learning-state-v2") ?? "null"))).toEqual(JSON.parse(saved));
  expect(await page.evaluate(() => JSON.parse(localStorage.getItem("kannada-buddy-learning-preferences-v2") ?? "null"))).toEqual(JSON.parse(preferences));
  await page.goto("/review");
  await page.reload();
  await expect(page.locator(".stat-card").filter({ hasText: "learning" }).locator("strong")).toHaveText("1");
});

test("find a situation and inspect draft provenance without changing learner progress", async ({ page }) => {
  await page.goto("/");
  const blockedRequest = page.waitForEvent("requestfailed", (request) => request.url() === "https://example.com/");
  expect(await page.evaluate(() => fetch("https://example.com/").then(() => true, () => false))).toBe(false);
  expect((await blockedRequest).failure()?.errorText).toMatch(/^net::ERR_BLOCKED_BY_CLIENT(?:\.Inspector)?$/);
  await page.goto("/travel");
  await expect(page.getByRole("heading", { name: "Prepare for your day", exact: true })).toBeVisible();
  await page.getByRole("link", { name: /Phone calls Find phrases/ }).click();
  await expect(page.getByRole("button", { name: "Phone calls", exact: true })).toHaveAttribute("aria-pressed", "true");
  await page.getByRole("searchbox", { name: "Search the course" }).fill("one moment");
  await expect(page.getByRole("status")).toHaveText("1 course phrase");
  await expect(page.getByText("One moment, please.", { exact: true })).toBeVisible();
  await expect(page.getByRole("link", { name: "Wikivoyage", exact: true })).toHaveAttribute("href", /^https:\/\//);
  await page.getByRole("searchbox").fill("no-such-course-item");
  await expect(page.getByText(/No matching course phrase/)).toBeVisible();
  await page.goto("/library");
  const draft = adminLibraryPhrases.find((phrase) => phrase.status === "ai_draft");
  if (!draft) throw new Error("The source-linked draft fixture is missing.");
  await page.getByRole("button", { name: /^ai draft \(/ }).click();
  await page.getByLabel("Source category", { exact: true }).selectOption(draft.category);
  await page.getByRole("searchbox").fill(draft.english);
  const card = page.locator("article").filter({ has: page.getByText(draft.english, { exact: true }) }).first();
  await expect(card.getByText("AI reference draft", { exact: true })).toBeVisible();
  await page.getByRole("searchbox").fill("no-such-reference-item");
  await expect(page.getByText("No phrases match this filter.", { exact: true })).toBeVisible();
  await page.getByRole("button", { name: "Clear filters", exact: true }).click();
  await expect(page.getByRole("button", { name: /^all references \(/ })).toHaveAttribute("aria-pressed", "true");
  await page.goto("/sources");
  await expect(page.getByRole("heading", { name: "Wikivoyage Kannada phrasebook", exact: true })).toBeVisible();
  await expect(page.getByText(/Content licensing does not certify native-speaker or audio review/)).toBeVisible();
  expect(await page.evaluate(() => localStorage.getItem("kannada-buddy-learning-state-v2"))).toBeNull();
});
